### PR TITLE
Abbreviations: remove dot if word is not an abbreviation

### PR DESCRIPTION
**Pull request by Terrtia**
- Add abbreviation set
- remove . if word is not an abbreviation

### CODE REVIEW

**Comment by pierotofy** [comment]
Thanks for the PR ! 

I'm not sure I'd want to start introducing such specific tokenization rules and additional pickle files. One of the goals of the projects is to keep the logic simple (and fast). Texts with more specific tokenization rules could be handled outside of lexilang (by performing tokenization, then calling lexilang individually on the tokens)?

**Comment by Terrtia** [comment]
How should we handle abbreviations ?

Punctuation needs to be removed to check if a word is in a dictionary. However, lexilang utilizes punctuation to distinguish Bulgarian and Hungarian languages, which is why I didn't removed dot characters in my previous PR.

I think It's interesting to detect languages through abbreviations. I use lexilang to identify languages in chat messages, which frequently include language-specific abbreviations.

**Comment by pierotofy** [comment]
One possible approach could be client applications could replace abbreviations with their full word equivalent before sending the text to lexilang for detection?

**Comment by Terrtia** [comment]
I've removed all abbreviations and dot characters."

**Comment by pierotofy** [comment]
Looks good, thanks!!

**Comment by Terrtia** [comment]
Thanks !
Could you please create a new release on PyPI ?

**Pull request merged**
